import json
import pytest
import httpx

from dota2_notify.clients.steam_client import SteamClient

@pytest.mark.asyncio
async def test_get_friends(httpx_mock):
    body = """{
    "friendslist": {
        "friends": [
            {
                "steamid": "76561198098445678",
                "relationship": "friend",
                "friend_since": 1546568438
            },
            {
                "steamid": "76561198153901234",
                "relationship": "friend",
                "friend_since": 1546295859
            }]
            }
            }
            """
    httpx_mock.add_response(url="https://api.steampowered.com/ISteamUser/GetFriendList/v1/?key=dummy_key&steamid=76561198882123456&relationship=friend", method="GET", json=json.loads(body))

    async with httpx.AsyncClient() as client:
        steam_client = SteamClient(api_key="dummy_key", client=client)
        response = await steam_client.get_friend_list(steam_id="76561198882123456")
        
        
        assert len(response) == 2
        assert response[0] == "76561198098445678"
        assert response[1] == "76561198153901234"


@pytest.mark.asyncio
async def test_get_player_summaries(httpx_mock):
    body = {
        "response": {
            "players": [
                {
                    "steamid": "76561198098445678",
                    "personaname": "Player1",
                    "profileurl": "https://steamcommunity.com/id/player1/",
                    "avatar": "https://avatars.steamstatic.com/avatar1.jpg"
                },
                {
                    "steamid": "76561198153901234",
                    "personaname": "Player2",
                    "profileurl": "https://steamcommunity.com/id/player2/",
                    "avatar": "https://avatars.steamstatic.com/avatar2.jpg"
                }
            ]
        }
    }
    httpx_mock.add_response(
        url="https://api.steampowered.com/ISteamUser/GetPlayerSummaries/v2/?key=dummy_key&steamids=76561198098445678%2C76561198153901234",
        method="GET",
        json=body
    )

    async with httpx.AsyncClient() as client:
        steam_client = SteamClient(api_key="dummy_key", client=client)
        response = await steam_client.get_player_summaries(steam_ids=["76561198098445678", "76561198153901234"])
        
        assert len(response) == 2
        assert response[0].steamid == "76561198098445678"
        assert response[0].personaname == "Player1"
        assert response[0].profileurl == "https://steamcommunity.com/id/player1/"
        assert response[0].avatar == "https://avatars.steamstatic.com/avatar1.jpg"
        assert response[1].steamid == "76561198153901234"
        assert response[1].personaname == "Player2"
        assert response[1].profileurl == "https://steamcommunity.com/id/player2/"
        assert response[1].avatar == "https://avatars.steamstatic.com/avatar2.jpg"

@pytest.mark.asyncio
async def test_validate_auth_request(httpx_mock):
    httpx_mock.add_response(
        url="https://steamcommunity.com/openid/login",
        method="POST",
        text="is_valid:true\n"
    )

    async with httpx.AsyncClient() as client:
        steam_client = SteamClient(api_key="dummy_key", client=client)
        params = {
            "openid.ns": "http://specs.openid.net/auth/2.0",
            "openid.claimed_id": "https://steamcommunity.com/openid/id/76561198882123456"
        }
        result = await steam_client.validate_auth_request(params)
        assert result is True

@pytest.mark.asyncio
async def test_validate_auth_request_raises_error(httpx_mock):
    httpx_mock.add_exception(httpx.RequestError("Connection failed"))

    async with httpx.AsyncClient() as client:
        steam_client = SteamClient(api_key="dummy_key", client=client)
        params = {
            "openid.ns": "http://specs.openid.net/auth/2.0",
            "openid.claimed_id": "https://steamcommunity.com/openid/id/76561198882123456"
        }
        result = await steam_client.validate_auth_request(params)
        assert result is False

@pytest.mark.asyncio
async def test_get_match_history_private_profile(httpx_mock):
    body = {
        "result": {
            "status": 15,
            "statusDetail": "Cannot get match history for a user that hasn't allowed it"
        }
    }
    httpx_mock.add_response(
        url="https://api.steampowered.com/IDOTA2Match_570/GetMatchHistory/v1/?account_id=76561198882123456&key=dummy_key",
        method="GET",
        json=body
    )

    async with httpx.AsyncClient() as client:
        steam_client = SteamClient(api_key="dummy_key", client=client)
        response, is_public = await steam_client.get_match_history(steam_id="76561198882123456")
        
        assert "result" in response
        assert response["result"]["status"] == 15
        assert response["result"]["statusDetail"] == "Cannot get match history for a user that hasn't allowed it"
        assert is_public is False

@pytest.mark.asyncio
async def test_get_match_history_public_profile(httpx_mock):
    body = {
        "result": {
            "status": 1,
            "num_results": 2,
            "total_results": 2,
            "results_remaining": 0,
            "matches": [
                {
                    "match_id": 7812345678,
                    "match_seq_num": 6543210987,
                    "start_time": 1707494400,
                    "lobby_type": 0,
                    "radiant_team_id": 0,
                    "dire_team_id": 0
                },
                {
                    "match_id": 7812345679,
                    "match_seq_num": 6543210988,
                    "start_time": 1707497000,
                    "lobby_type": 0,
                    "radiant_team_id": 0,
                    "dire_team_id": 0
                }
            ]
        }
    }
    httpx_mock.add_response(
        url="https://api.steampowered.com/IDOTA2Match_570/GetMatchHistory/v1/?account_id=76561198882123456&key=dummy_key",
        method="GET",
        json=body
    )

    async with httpx.AsyncClient() as client:
        steam_client = SteamClient(api_key="dummy_key", client=client)
        response, is_public = await steam_client.get_match_history(steam_id="76561198882123456")
        
        assert "result" in response
        assert response["result"]["status"] == 1
        assert response["result"]["num_results"] == 2
        assert len(response["result"]["matches"]) == 2
        assert response["result"]["matches"][0]["match_id"] == 7812345678
        assert response["result"]["matches"][1]["match_id"] == 7812345679
        assert is_public is True

@pytest.mark.asyncio
async def test_get_match_history_by_sequence_num(httpx_mock):
    body = {
    "result": {
        "status": 1,
        "matches": [
            {
                "players": [
                    {
                        "account_id": 4294967295,
                        "player_slot": 0,
                        "team_number": 0,
                        "team_slot": 0,
                        "hero_id": 29,
                        "hero_variant": 2,
                        "item_0": 50,
                        "item_1": 108,
                        "item_2": 73,
                        "item_3": 1,
                        "item_4": 112,
                        "item_5": 81,
                        "backpack_0": 11,
                        "backpack_1": 0,
                        "backpack_2": 0,
                        "item_neutral": 1643,
                        "item_neutral2": 1585,
                        "kills": 6,
                        "deaths": 4,
                        "assists": 24,
                        "leaver_status": 0,
                        "last_hits": 172,
                        "denies": 6,
                        "gold_per_min": 461,
                        "xp_per_min": 712,
                        "level": 23,
                        "net_worth": 17967,
                        "aghanims_scepter": 0,
                        "aghanims_shard": 0,
                        "moonshard": 0,
                        "hero_damage": 17067,
                        "tower_damage": 5887,
                        "hero_healing": 3085,
                        "gold": 1987,
                        "gold_spent": 16730,
                        "scaled_hero_damage": 11164,
                        "scaled_tower_damage": 2761,
                        "scaled_hero_healing": 1096,
                    },
                    {
                        "account_id": 4294967295,
                        "player_slot": 1,
                        "team_number": 0,
                        "team_slot": 1,
                        "hero_id": 87,
                        "hero_variant": 1,
                        "item_0": 214,
                        "item_1": 232,
                        "item_2": 108,
                        "item_3": 38,
                        "item_4": 43,
                        "item_5": 4205,
                        "backpack_0": 0,
                        "backpack_1": 0,
                        "backpack_2": 0,
                        "item_neutral": 1168,
                        "item_neutral2": 1585,
                        "kills": 7,
                        "deaths": 6,
                        "assists": 19,
                        "leaver_status": 0,
                        "last_hits": 128,
                        "denies": 2,
                        "gold_per_min": 409,
                        "xp_per_min": 603,
                        "level": 21,
                        "net_worth": 12957,
                        "aghanims_scepter": 0,
                        "aghanims_shard": 1,
                        "moonshard": 0,
                        "hero_damage": 19502,
                        "tower_damage": 684,
                        "hero_healing": 0,
                        "gold": 3632,
                        "gold_spent": 11635,
                        "scaled_hero_damage": 11844,
                        "scaled_tower_damage": 327,
                        "scaled_hero_healing": 0,
                    },
                    {
                        "account_id": 4294967295,
                        "player_slot": 2,
                        "team_number": 0,
                        "team_slot": 2,
                        "hero_id": 5,
                        "hero_variant": 3,
                        "item_0": 0,
                        "item_1": 1,
                        "item_2": 254,
                        "item_3": 214,
                        "item_4": 102,
                        "item_5": 244,
                        "backpack_0": 0,
                        "backpack_1": 0,
                        "backpack_2": 0,
                        "item_neutral": 1720,
                        "item_neutral2": 1583,
                        "kills": 5,
                        "deaths": 7,
                        "assists": 29,
                        "leaver_status": 0,
                        "last_hits": 47,
                        "denies": 1,
                        "gold_per_min": 370,
                        "xp_per_min": 647,
                        "level": 22,
                        "net_worth": 13150,
                        "aghanims_scepter": 0,
                        "aghanims_shard": 1,
                        "moonshard": 0,
                        "hero_damage": 14981,
                        "tower_damage": 1658,
                        "hero_healing": 0,
                        "gold": 3725,
                        "gold_spent": 11270,
                        "scaled_hero_damage": 11483,
                        "scaled_tower_damage": 609,
                        "scaled_hero_healing": 0,
                    },
                    {
                        "account_id": 4294967295,
                        "player_slot": 3,
                        "team_number": 0,
                        "team_slot": 3,
                        "hero_id": 88,
                        "hero_variant": 1,
                        "item_0": 204,
                        "item_1": 21,
                        "item_2": 123,
                        "item_3": 180,
                        "item_4": 143,
                        "item_5": 36,
                        "backpack_0": 41,
                        "backpack_1": 0,
                        "backpack_2": 0,
                        "item_neutral": 1638,
                        "item_neutral2": 1586,
                        "kills": 15,
                        "deaths": 2,
                        "assists": 15,
                        "leaver_status": 0,
                        "last_hits": 161,
                        "denies": 13,
                        "gold_per_min": 507,
                        "xp_per_min": 698,
                        "level": 22,
                        "net_worth": 20248,
                        "aghanims_scepter": 0,
                        "aghanims_shard": 0,
                        "moonshard": 0,
                        "hero_damage": 25483,
                        "tower_damage": 3110,
                        "hero_healing": 0,
                        "gold": 1538,
                        "gold_spent": 19110,
                        "scaled_hero_damage": 18696,
                        "scaled_tower_damage": 1533,
                        "scaled_hero_healing": 0,
                    },
                    {
                        "account_id": 4294967295,
                        "player_slot": 4,
                        "team_number": 0,
                        "team_slot": 4,
                        "hero_id": 44,
                        "hero_variant": 3,
                        "item_0": 156,
                        "item_1": 145,
                        "item_2": 117,
                        "item_3": 168,
                        "item_4": 63,
                        "item_5": 143,
                        "backpack_0": 0,
                        "backpack_1": 36,
                        "backpack_2": 116,
                        "item_neutral": 1643,
                        "item_neutral2": 1584,
                        "kills": 10,
                        "deaths": 7,
                        "assists": 12,
                        "leaver_status": 0,
                        "last_hits": 378,
                        "denies": 0,
                        "gold_per_min": 652,
                        "xp_per_min": 903,
                        "level": 25,
                        "net_worth": 25855,
                        "aghanims_scepter": 0,
                        "aghanims_shard": 1,
                        "moonshard": 0,
                        "hero_damage": 29561,
                        "tower_damage": 14325,
                        "hero_healing": 0,
                        "gold": 3220,
                        "gold_spent": 22790,
                        "scaled_hero_damage": 17391,
                        "scaled_tower_damage": 6228,
                        "scaled_hero_healing": 0,
                    },
                    {
                        "account_id": 4294967295,
                        "player_slot": 128,
                        "team_number": 1,
                        "team_slot": 0,
                        "hero_id": 26,
                        "hero_variant": 2,
                        "item_0": 214,
                        "item_1": 108,
                        "item_2": 1,
                        "item_3": 0,
                        "item_4": 0,
                        "item_5": 57,
                        "backpack_0": 233,
                        "backpack_1": 0,
                        "backpack_2": 0,
                        "item_neutral": 1605,
                        "item_neutral2": 1583,
                        "kills": 3,
                        "deaths": 9,
                        "assists": 14,
                        "leaver_status": 0,
                        "last_hits": 41,
                        "denies": 4,
                        "gold_per_min": 244,
                        "xp_per_min": 446,
                        "level": 18,
                        "net_worth": 9278,
                        "aghanims_scepter": 0,
                        "aghanims_shard": 0,
                        "moonshard": 0,
                        "hero_damage": 10306,
                        "tower_damage": 232,
                        "hero_healing": 0,
                        "gold": 453,
                        "gold_spent": 9710,
                        "scaled_hero_damage": 7465,
                        "scaled_tower_damage": 130,
                        "scaled_hero_healing": 0,
                    },
                    {
                        "account_id": 4294967295,
                        "player_slot": 129,
                        "team_number": 1,
                        "team_slot": 1,
                        "hero_id": 2,
                        "hero_variant": 2,
                        "item_0": 1107,
                        "item_1": 127,
                        "item_2": 1,
                        "item_3": 116,
                        "item_4": 36,
                        "item_5": 29,
                        "backpack_0": 0,
                        "backpack_1": 11,
                        "backpack_2": 0,
                        "item_neutral": 1599,
                        "item_neutral2": 1595,
                        "kills": 9,
                        "deaths": 12,
                        "assists": 10,
                        "leaver_status": 0,
                        "last_hits": 189,
                        "denies": 9,
                        "gold_per_min": 419,
                        "xp_per_min": 490,
                        "level": 19,
                        "net_worth": 14573,
                        "aghanims_scepter": 0,
                        "aghanims_shard": 0,
                        "moonshard": 0,
                        "hero_damage": 26321,
                        "tower_damage": 28,
                        "hero_healing": 0,
                        "gold": 2313,
                        "gold_spent": 13095,
                        "scaled_hero_damage": 18058,
                        "scaled_tower_damage": 14,
                        "scaled_hero_healing": 0,
                    },
                    {
                        "account_id": 1430162649,
                        "player_slot": 130,
                        "team_number": 1,
                        "team_slot": 2,
                        "hero_id": 58,
                        "hero_variant": 1,
                        "item_0": 692,
                        "item_1": 7,
                        "item_2": 0,
                        "item_3": 263,
                        "item_4": 36,
                        "item_5": 63,
                        "backpack_0": 0,
                        "backpack_1": 0,
                        "backpack_2": 0,
                        "item_neutral": 1599,
                        "item_neutral2": 1576,
                        "kills": 4,
                        "deaths": 6,
                        "assists": 3,
                        "leaver_status": 0,
                        "last_hits": 162,
                        "denies": 7,
                        "gold_per_min": 309,
                        "xp_per_min": 421,
                        "level": 17,
                        "net_worth": 11451,
                        "aghanims_scepter": 0,
                        "aghanims_shard": 0,
                        "moonshard": 0,
                        "hero_damage": 8078,
                        "tower_damage": 107,
                        "hero_healing": 360,
                        "gold": 441,
                        "gold_spent": 11735,
                        "scaled_hero_damage": 5698,
                        "scaled_tower_damage": 44,
                        "scaled_hero_healing": 132,
                    },
                    {
                        "account_id": 922037303,
                        "player_slot": 131,
                        "team_number": 1,
                        "team_slot": 3,
                        "hero_id": 35,
                        "hero_variant": 1,
                        "item_0": 263,
                        "item_1": 158,
                        "item_2": 0,
                        "item_3": 75,
                        "item_4": 249,
                        "item_5": 63,
                        "backpack_0": 0,
                        "backpack_1": 0,
                        "backpack_2": 0,
                        "item_neutral": 1605,
                        "item_neutral2": 1576,
                        "kills": 7,
                        "deaths": 9,
                        "assists": 10,
                        "leaver_status": 0,
                        "last_hits": 271,
                        "denies": 9,
                        "gold_per_min": 495,
                        "xp_per_min": 622,
                        "level": 21,
                        "net_worth": 18966,
                        "aghanims_scepter": 0,
                        "aghanims_shard": 0,
                        "moonshard": 0,
                        "hero_damage": 22304,
                        "tower_damage": 477,
                        "hero_healing": 0,
                        "gold": 1311,
                        "gold_spent": 18605,
                        "scaled_hero_damage": 15782,
                        "scaled_tower_damage": 332,
                        "scaled_hero_healing": 0,
                    },
                    {
                        "account_id": 192852394,
                        "player_slot": 132,
                        "team_number": 1,
                        "team_slot": 4,
                        "hero_id": 155,
                        "hero_variant": 1,
                        "item_0": 36,
                        "item_1": 261,
                        "item_2": 0,
                        "item_3": 267,
                        "item_4": 180,
                        "item_5": 79,
                        "backpack_0": 0,
                        "backpack_1": 0,
                        "backpack_2": 0,
                        "item_neutral": 1158,
                        "item_neutral2": 1577,
                        "kills": 3,
                        "deaths": 8,
                        "assists": 13,
                        "leaver_status": 1,
                        "last_hits": 82,
                        "denies": 7,
                        "gold_per_min": 277,
                        "xp_per_min": 449,
                        "level": 18,
                        "net_worth": 9388,
                        "aghanims_scepter": 0,
                        "aghanims_shard": 1,
                        "moonshard": 0,
                        "hero_damage": 11466,
                        "tower_damage": 0,
                        "hero_healing": 2301,
                        "gold": 978,
                        "gold_spent": 9880,
                        "scaled_hero_damage": 8214,
                        "scaled_tower_damage": 0,
                        "scaled_hero_healing": 1086,
                    }
                ],
                "radiant_win": True,
                "duration": 2416,
                "pre_game_duration": 90,
                "start_time": 1769292268,
                "match_id": 8663080015,
                "match_seq_num": 7277253262,
                "tower_status_radiant": 1975,
                "tower_status_dire": 256,
                "barracks_status_radiant": 63,
                "barracks_status_dire": 48,
                "cluster": 410,
                "first_blood_time": 154,
                "lobby_type": 0,
                "human_players": 10,
                "leagueid": 0,
                "game_mode": 22,
                "flags": 1,
                "engine": 1,
                "radiant_score": 44,
                "dire_score": 26,
            },
            {
                "players": [
                    {
                        "account_id": 819130378,
                        "player_slot": 0,
                        "team_number": 0,
                        "team_slot": 0,
                        "hero_id": 107,
                        "hero_variant": 4,
                        "item_0": 16,
                        "item_1": 214,
                        "item_2": 1122,
                        "item_3": 92,
                        "item_4": 218,
                        "item_5": 0,
                        "backpack_0": 0,
                        "backpack_1": 0,
                        "backpack_2": 0,
                        "item_neutral": 2097,
                        "item_neutral2": 1585,
                        "kills": 3,
                        "deaths": 8,
                        "assists": 3,
                        "leaver_status": 1,
                        "last_hits": 22,
                        "denies": 1,
                        "gold_per_min": 179,
                        "xp_per_min": 174,
                        "level": 9,
                        "net_worth": 2833,
                        "aghanims_scepter": 0,
                        "aghanims_shard": 0,
                        "moonshard": 0,
                        "hero_damage": 7711,
                        "tower_damage": 0,
                        "hero_healing": 600,
                        "gold": 3,
                        "gold_spent": 3655,
                        "scaled_hero_damage": 7398,
                        "scaled_tower_damage": 0,
                        "scaled_hero_healing": 452,
                    },
                    {
                        "account_id": 115922161,
                        "player_slot": 1,
                        "team_number": 0,
                        "team_slot": 1,
                        "hero_id": 41,
                        "hero_variant": 2,
                        "item_0": 63,
                        "item_1": 75,
                        "item_2": 166,
                        "item_3": 11,
                        "item_4": 139,
                        "item_5": 36,
                        "backpack_0": 0,
                        "backpack_1": 0,
                        "backpack_2": 0,
                        "item_neutral": 1638,
                        "item_neutral2": 1585,
                        "kills": 6,
                        "deaths": 6,
                        "assists": 3,
                        "leaver_status": 2,
                        "last_hits": 95,
                        "denies": 16,
                        "gold_per_min": 449,
                        "xp_per_min": 634,
                        "level": 19,
                        "net_worth": 12696,
                        "aghanims_scepter": 0,
                        "aghanims_shard": 0,
                        "moonshard": 0,
                        "hero_damage": 8935,
                        "tower_damage": 0,
                        "hero_healing": 0,
                        "gold": 1731,
                        "gold_spent": 11300,
                        "scaled_hero_damage": 5629,
                        "scaled_tower_damage": 0,
                        "scaled_hero_healing": 0,
                    },
                    {
                        "account_id": 455148711,
                        "player_slot": 2,
                        "team_number": 0,
                        "team_slot": 2,
                        "hero_id": 2,
                        "hero_variant": 2,
                        "item_0": 0,
                        "item_1": 0,
                        "item_2": 0,
                        "item_3": 0,
                        "item_4": 0,
                        "item_5": 0,
                        "backpack_0": 0,
                        "backpack_1": 0,
                        "backpack_2": 0,
                        "item_neutral": 1717,
                        "item_neutral2": 1585,
                        "kills": 2,
                        "deaths": 9,
                        "assists": 3,
                        "leaver_status": 1,
                        "last_hits": 78,
                        "denies": 10,
                        "gold_per_min": 225,
                        "xp_per_min": 256,
                        "level": 11,
                        "net_worth": 1,
                        "aghanims_scepter": 0,
                        "aghanims_shard": 0,
                        "moonshard": 0,
                        "hero_damage": 7182,
                        "tower_damage": 0,
                        "hero_healing": 0,
                        "gold": 1,
                        "gold_spent": 4955,
                        "scaled_hero_damage": 7647,
                        "scaled_tower_damage": 0,
                        "scaled_hero_healing": 0,
                    },
                    {
                        "account_id": 1484364939,
                        "player_slot": 3,
                        "team_number": 0,
                        "team_slot": 3,
                        "hero_id": 25,
                        "hero_variant": 2,
                        "item_0": 29,
                        "item_1": 16,
                        "item_2": 16,
                        "item_3": 77,
                        "item_4": 16,
                        "item_5": 4204,
                        "backpack_0": 149,
                        "backpack_1": 0,
                        "backpack_2": 0,
                        "item_neutral": 0,
                        "item_neutral2": 0,
                        "kills": 0,
                        "deaths": 22,
                        "assists": 2,
                        "leaver_status": 0,
                        "last_hits": 25,
                        "denies": 1,
                        "gold_per_min": 242,
                        "xp_per_min": 298,
                        "level": 13,
                        "net_worth": 6754,
                        "aghanims_scepter": 0,
                        "aghanims_shard": 0,
                        "moonshard": 0,
                        "hero_damage": 4342,
                        "tower_damage": 0,
                        "hero_healing": 0,
                        "gold": 634,
                        "gold_spent": 6375,
                        "scaled_hero_damage": 4306,
                        "scaled_tower_damage": 0,
                        "scaled_hero_healing": 0,
                    },
                    {
                        "account_id": 0,
                        "player_slot": 4,
                        "team_number": 0,
                        "team_slot": 4,
                        "hero_id": 16,
                        "hero_variant": 4,
                        "item_0": 36,
                        "item_1": 119,
                        "item_2": 1,
                        "item_3": 180,
                        "item_4": 73,
                        "item_5": 0,
                        "backpack_0": 0,
                        "backpack_1": 0,
                        "backpack_2": 0,
                        "item_neutral": 565,
                        "item_neutral2": 1586,
                        "kills": 4,
                        "deaths": 16,
                        "assists": 5,
                        "leaver_status": 0,
                        "last_hits": 100,
                        "denies": 0,
                        "gold_per_min": 484,
                        "xp_per_min": 568,
                        "level": 18,
                        "net_worth": 12545,
                        "aghanims_scepter": 0,
                        "aghanims_shard": 1,
                        "moonshard": 0,
                        "hero_damage": 31849,
                        "tower_damage": 0,
                        "hero_healing": 0,
                        "gold": 1255,
                        "gold_spent": 11745,
                        "scaled_hero_damage": 20091,
                        "scaled_tower_damage": 0,
                        "scaled_hero_healing": 0,
                    },
                    {
                        "account_id": 153374464,
                        "player_slot": 128,
                        "team_number": 1,
                        "team_slot": 0,
                        "hero_id": 6,
                        "hero_variant": 1,
                        "item_0": 0,
                        "item_1": 139,
                        "item_2": 75,
                        "item_3": 63,
                        "item_4": 141,
                        "item_5": 263,
                        "backpack_0": 0,
                        "backpack_1": 0,
                        "backpack_2": 0,
                        "item_neutral": 1605,
                        "item_neutral2": 1584,
                        "kills": 17,
                        "deaths": 2,
                        "assists": 12,
                        "leaver_status": 0,
                        "last_hits": 248,
                        "denies": 18,
                        "gold_per_min": 699,
                        "xp_per_min": 844,
                        "level": 22,
                        "net_worth": 21595,
                        "aghanims_scepter": 0,
                        "aghanims_shard": 0,
                        "moonshard": 0,
                        "hero_damage": 23047,
                        "tower_damage": 15082,
                        "hero_healing": 0,
                        "gold": 4490,
                        "gold_spent": 17955,
                        "scaled_hero_damage": 21066,
                        "scaled_tower_damage": 7135,
                        "scaled_hero_healing": 0,
                    },
                    {
                        "account_id": 106186543,
                        "player_slot": 129,
                        "team_number": 1,
                        "team_slot": 1,
                        "hero_id": 33,
                        "hero_variant": 1,
                        "item_0": 69,
                        "item_1": 259,
                        "item_2": 1,
                        "item_3": 244,
                        "item_4": 180,
                        "item_5": 43,
                        "backpack_0": 0,
                        "backpack_1": 0,
                        "backpack_2": 0,
                        "item_neutral": 1158,
                        "item_neutral2": 1577,
                        "kills": 4,
                        "deaths": 7,
                        "assists": 29,
                        "leaver_status": 0,
                        "last_hits": 38,
                        "denies": 2,
                        "gold_per_min": 341,
                        "xp_per_min": 540,
                        "level": 17,
                        "net_worth": 10028,
                        "aghanims_scepter": 0,
                        "aghanims_shard": 1,
                        "moonshard": 0,
                        "hero_damage": 16483,
                        "tower_damage": 1474,
                        "hero_healing": 0,
                        "gold": 1103,
                        "gold_spent": 9620,
                        "scaled_hero_damage": 13512,
                        "scaled_tower_damage": 683,
                        "scaled_hero_healing": 0,
                    },
                    {
                        "account_id": 4294967295,
                        "player_slot": 130,
                        "team_number": 1,
                        "team_slot": 2,
                        "hero_id": 86,
                        "hero_variant": 1,
                        "item_0": 180,
                        "item_1": 36,
                        "item_2": 201,
                        "item_3": 108,
                        "item_4": 73,
                        "item_5": 244,
                        "backpack_0": 42,
                        "backpack_1": 216,
                        "backpack_2": 0,
                        "item_neutral": 1604,
                        "item_neutral2": 1577,
                        "kills": 13,
                        "deaths": 0,
                        "assists": 18,
                        "leaver_status": 0,
                        "last_hits": 90,
                        "denies": 5,
                        "gold_per_min": 479,
                        "xp_per_min": 745,
                        "level": 21,
                        "net_worth": 14885,
                        "aghanims_scepter": 0,
                        "aghanims_shard": 0,
                        "moonshard": 0,
                        "hero_damage": 19824,
                        "tower_damage": 2577,
                        "hero_healing": 194,
                        "gold": 4080,
                        "gold_spent": 12925,
                        "scaled_hero_damage": 16209,
                        "scaled_tower_damage": 1317,
                        "scaled_hero_healing": 203,
                    },
                    {
                        "account_id": 4294967295,
                        "player_slot": 131,
                        "team_number": 1,
                        "team_slot": 3,
                        "hero_id": 63,
                        "hero_variant": 2,
                        "item_0": 123,
                        "item_1": 168,
                        "item_2": 36,
                        "item_3": 154,
                        "item_4": 166,
                        "item_5": 63,
                        "backpack_0": 0,
                        "backpack_1": 0,
                        "backpack_2": 0,
                        "item_neutral": 2097,
                        "item_neutral2": 1586,
                        "kills": 19,
                        "deaths": 6,
                        "assists": 7,
                        "leaver_status": 0,
                        "last_hits": 152,
                        "denies": 1,
                        "gold_per_min": 567,
                        "xp_per_min": 846,
                        "level": 22,
                        "net_worth": 18152,
                        "aghanims_scepter": 0,
                        "aghanims_shard": 0,
                        "moonshard": 0,
                        "hero_damage": 26138,
                        "tower_damage": 5770,
                        "hero_healing": 0,
                        "gold": 742,
                        "gold_spent": 17600,
                        "scaled_hero_damage": 22238,
                        "scaled_tower_damage": 2819,
                        "scaled_hero_healing": 0,
                    },
                    {
                        "account_id": 4294967295,
                        "player_slot": 132,
                        "team_number": 1,
                        "team_slot": 4,
                        "hero_id": 7,
                        "hero_variant": 3,
                        "item_0": 123,
                        "item_1": 149,
                        "item_2": 1,
                        "item_3": 180,
                        "item_4": 145,
                        "item_5": 0,
                        "backpack_0": 0,
                        "backpack_1": 0,
                        "backpack_2": 0,
                        "item_neutral": 1603,
                        "item_neutral2": 1585,
                        "kills": 8,
                        "deaths": 1,
                        "assists": 16,
                        "leaver_status": 0,
                        "last_hits": 166,
                        "denies": 14,
                        "gold_per_min": 500,
                        "xp_per_min": 664,
                        "level": 19,
                        "net_worth": 15894,
                        "aghanims_scepter": 0,
                        "aghanims_shard": 0,
                        "moonshard": 0,
                        "hero_damage": 14422,
                        "tower_damage": 3393,
                        "hero_healing": 0,
                        "gold": 1544,
                        "gold_spent": 15220,
                        "scaled_hero_damage": 13285,
                        "scaled_tower_damage": 2173,
                        "scaled_hero_healing": 0,
                    }
                ],
                "radiant_win": False,
                "duration": 1908,
                "pre_game_duration": 90,
                "start_time": 1769292758,
                "match_id": 8663087567,
                "match_seq_num": 7277253263,
                "tower_status_radiant": 0,
                "tower_status_dire": 2047,
                "barracks_status_radiant": 0,
                "barracks_status_dire": 63,
                "cluster": 191,
                "first_blood_time": 0,
                "lobby_type": 0,
                "human_players": 10,
                "leagueid": 0,
                "game_mode": 22,
                "flags": 1,
                "engine": 1,
                "radiant_score": 16,
                "dire_score": 61,
            }
        ]
    }
}
    httpx_mock.add_response(
        url="https://api.steampowered.com/IDOTA2Match_570/GetMatchHistoryBySequenceNum/v1/?start_at_match_seq_num=12345&matches_requested=100&key=dummy_key",
        method="GET",
        json=body
    )

    async with httpx.AsyncClient() as client:
        steam_client = SteamClient(api_key="dummy_key", client=client)
        response = await steam_client.get_match_history_by_sequence_num(start_at_match_seq_num=12345)
        
        assert response.result.status == 1
        assert len(response.result.matches) == 2
        
        match1 = response.result.matches[0]
        assert match1.match_id == 8663080015
        assert match1.radiant_win is True
        assert len(match1.players) == 10
        assert match1.players[0].account_id == 4294967295
        assert match1.players[0].hero_id == 29
        
        match2 = response.result.matches[1]
        assert match2.match_id == 8663087567
        assert match2.radiant_win is False
        assert len(match2.players) == 10
        assert match2.players[4].account_id == 0
        assert match2.players[4].hero_id == 16